version: "3.8"

services:
  postgres:
    image: postgres
    #container_name: servidorWebPostgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./database:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
  apache:
    image: php:latest
    build: .
    #container_name: servicioPHP
    ports:
      - "80:80"
    volumes:
      - ./webs/:/var/www/html

    links:
      - postgres
    